using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using CodeCasing;
using Microsoft.CodeAnalysis;

namespace Blazicons.Generating;

public static class GeneratorExecutionContextExtensions
{
    public static void WriteIconsClass(
        this GeneratorExecutionContext context,
        string className,
        string svgFolder,
        string searchPattern = "*.svg",
        Func<string, string>? propertyNameFromFileName = null,
        Func<string, bool>? isFileNameOk = null
        )
    {
        propertyNameFromFileName ??= GetMemberName;

        var builder = new StringBuilder();

        builder.AppendLine("// <autogenerated/>");
        builder.AppendLine("namespace Blazicons;"); // Use Target Namespace

        builder.AppendLine($"public static class {className}");
        builder.AppendLine("{");

        var files = Directory.GetFiles(svgFolder, searchPattern, SearchOption.AllDirectories);

        if (isFileNameOk is not null)
        {
            files = files.Where(x => isFileNameOk(x)).ToArray();
        }

        var propertyNames = new List<string>();
        foreach (var file in files)
        {
            var svg = File.ReadAllText(Path.Combine(svgFolder, file));
            var svgString = ScrubSvg(svg);
            var viewBox = GetViewBox(svg);
            var propertyName = ScrubPropertyName(propertyNameFromFileName(file));
            propertyNames.Add(propertyName);
            builder.Append($"public static SvgIcon {propertyName} => SvgIcon.FromContent(\"{svgString}\"");
            if (!string.IsNullOrEmpty(viewBox))
            {
                builder.Append($", \"{viewBox}\"");
            }
            builder.AppendLine(");");
        }

        builder.AppendLine("}");
        context.AddSource($"{className}.g.cs", builder.ToString());
    }

    private static string? GetViewBox(string svg)
    {
        var regex = new Regex("<svg.*viewBox=\"([^\"]*)\"", RegexOptions.Singleline);
        var match = regex.Match(svg);
        if (match.Success)
        {
            return match.Groups[1].Value;
        }

        return null;
    }

    private static string ScrubSvg(string svg)
    {
        svg = Regex.Replace(svg, @"<\/?svg[^>]*>", string.Empty);
        svg = Regex.Replace(svg, @"<!--(.*?)-->", string.Empty);
        svg = Regex.Replace(svg, "fill=\"[^\"]*\"", string.Empty);
        svg = Regex.Replace(svg, "stroke:#000;", "stroke:currentColor;");
        svg = Regex.Replace(svg, "stroke=\"#000\"", "stroke=\"currentColor\"");

        svg = svg.Replace("\n", string.Empty).Replace("\r", string.Empty);
        return svg.Replace("\\", "\\\\").Replace("\"", "\\\"").Trim();
    }

    private static string ScrubPropertyName(string name)
    {
        var result = name;

        switch (result[0])
        {
            case '1':
                result = $"One{result.Substring(1)}";
                break;

            case '2':
                result = $"Two{result.Substring(1)}";
                break;

            case '3':
                result = $"Three{result.Substring(1)}";
                break;

            case '4':
                result = $"Four{result.Substring(1)}";
                break;

            case '5':
                result = $"Five{result.Substring(1)}";
                break;

            case '6':
                result = $"Six{result.Substring(1)}";
                break;

            case '7':
                result = $"Seven{result.Substring(1)}";
                break;

            case '8':
                result = $"Eight{result.Substring(1)}";
                break;

            case '9':
                result = $"Nine{result.Substring(1)}";
                break;

            case '0':
                result = $"Zero{result.Substring(1)}";
                break;

            default:
                break;
        }

        return result;
    }

    private static string GetMemberName(string fileName)
    {
        return Path.GetFileNameWithoutExtension(fileName).ToPascalCase();
    }
}